// <auto-generated />
namespace HMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _202006131622112_AddPictures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202006131622112_AddPictures));
        
        string IMigrationMetadata.Id
        {
            get { return "202006141759103_202006131622112_AddPictures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
